# Generated by Django 3.1.7 on 2021-04-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantWatering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='assignedToPlant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantWatering.plant'),
        ),
        migrations.AlterField(
            model_name='soilsensor',
            name='assignedToPlant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantWatering.plant'),
        ),
    ]
