# Generated by Django 3.1.7 on 2021-04-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantWatering', '0002_auto_20210413_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilsensor',
            name='analogInputNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilsensor',
            name='i2cAddr',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
