# Generated by Django 3.1.7 on 2021-04-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantWatering', '0003_auto_20210413_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='assignedToPlant',
        ),
        migrations.RemoveField(
            model_name='soilsensor',
            name='assignedToPlant',
        ),
    ]
