# Generated by Django 3.1.7 on 2021-04-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantWatering', '0004_auto_20210414_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantWatering.pump'),
        ),
        migrations.AddField(
            model_name='plant',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantWatering.soilsensor'),
        ),
    ]
