# Generated by Django 3.1.7 on 2021-04-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantWatering', '0006_auto_20210414_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='name',
            field=models.CharField(default='temp', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soilsensor',
            name='name',
            field=models.CharField(default='temp', max_length=25),
            preserve_default=False,
        ),
    ]
