# Generated by Django 3.1.7 on 2021-04-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantWatering', '0007_auto_20210414_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='name',
        ),
        migrations.RemoveField(
            model_name='soilsensor',
            name='name',
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soilsensor',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pump',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soilsensor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
