# Generated by Django 3.1.7 on 2021-04-14 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantWatering', '0008_auto_20210414_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logDateTime', models.DateTimeField(auto_now_add=True)),
                ('durationSeconds', models.IntegerField()),
                ('moistureLevel', models.IntegerField(blank=True, null=True)),
                ('triggeredBy', models.CharField(default='System', max_length=50)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantWatering.plant')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantWatering.pump')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantWatering.soilsensor')),
            ],
        ),
    ]
