# Generated by Django 3.1.7 on 2021-04-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantWatering', '0010_auto_20210414_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='waterDurationSeconds',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='waterFrequencyDays',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
