# Generated by Django 3.1.7 on 2021-04-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantWatering', '0011_auto_20210421_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plantPhotos/'),
        ),
    ]
